### ISSUE TITLE
recovery if queue gets wiped out

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/datasets#12]
If we've updated the "last completed at" date but the queue later gets wiped out, how would we recover from this? There are a couple options:

- Keep a log of "last completed at" dates so you could roll back to the last known good one. Potentially, mark each of those as actually known finished when all jobs in the queue have completed successfully

- OR (probably better and ultimately wanted anyway) just have a way of checking the filesystem for the current state and queueing jobs based on the required changes instead of just based on a "last completed at" date.

**Comment by malakai97** [comment]
+1 for logging the last_run_times that have been used (in practice, these would be datetime ranges).

Would we expect the run time of a `find` over the entire filesystem to be fast enough to be useful?

**Comment by aelkiss** [comment]
@malakai97  says: 

"Specifically, I think we can address #10 and #12 simultaneously.  The plan would be to have `Datasets::Scheduler#add` and `#delete` return the Volumes for which a job was enqueued.  This is the superset of what changed that I was talking about in the ticket.

The caller would then pass that information to a formatter or something, that writes to a file.  We're then able to use that file to determine things like "what was enqueued" and what the last date range was."

**Comment by aelkiss** [comment]
@malakai97 For testing the scheduler I wonder if we should look at https://github.com/leshill/resque_spec  (might be stale though) - I took a look at how you were testing jobs in DPN and it looks like that's using ActiveJob rather than resque directly, so we need a different approach here. Resque also doesn't support passing non-JSONable objects as arguments to jobs, so we need a way to serialize `Volume` and `VolumeWriter` objects for queueing (maybe you're already working on this?)

**Comment by malakai97** [comment]
It's super stale :boomparrot:

In general, resque's functionality is a superset of ActiveJob's, as ActiveJob only supports things that are common among the various adapters.  

Setting `Resque.inline = true` gets us what we need in terms of not _actually_ enqueuing things.  From there, rspec-mocks seems sufficient to test that things were or were not enqueued.
