### ISSUE TITLE
inconsistent naming between Create job, Scheduler, VolumeWriter

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/datasets#38]
`CreateJob` vs `Scheduler#add` vs `VolumeWriter.save` is not consistent; `DeleteJob` vs `Scheduler#delete` vs `VolumeWriter#delete` is consistent.

**Comment by malakai97** [comment]
CreateJob renamed to SaveJob in feature/jobs

`Scheduler#save` may be unclear; Scheduler itself may be more aptly named Queuer or Enqueuer.  Methods could then be `#add_saves` and `#add_deletes`.  Other verbs may be more apt, e.g. `s/add/queue`, `s/add/enqueue`.

**Comment by aelkiss** [comment]
Let's address this more in a later refactoring pass.

**Comment by aelkiss** [comment]
Migrated to HTREPO-117
