### ISSUE TITLE
Configure failed jobs to requeue automatically

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/datasets#5]
- re-try failed resque jobs
- look at the failures and try to figure out what's going on

**Comment by malakai97** [comment]
https://github.com/lantins/resque-retry

**Comment by malakai97** [comment]
Tentatively complete with resque-retry in lib/datasets/jobs/job.rb; needs testing.

**Comment by aelkiss** [comment]
Related to #53 (currently requires redis be running for tests to pass)

**Comment by aelkiss** [comment]
I was seeing some issues in testing where it looked like jobs were failing, then the re-queue failed because it was not setting them to a queue. I think I mentioned this on Slack but this seems like a good place to record it too.

**Comment by aelkiss** [comment]
I'd still like to test this a little more. There are some issues with Redis connections to look into, and I'd still like to run kind of a complete pipeline where:

- ensure the source path is missing, so create jobs will fail
- queue some material, see failures
- put source path back in place
- things should be re-queued and succeed.

**Comment by aelkiss** [comment]
https://github.com/hathitrust/datasets/commit/599249e3490eb9b44b7083aa1878e74030317260 addresses the issue with things not being put back into a queue (see convo on slack with frustration around how resque expects every class to have a single static queue).

**Comment by aelkiss** [comment]
Tested; if we see failures sticking around we can revisit.
