### ISSUE TITLE
Configure resque-scheduler

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/datasets#7]
- all schedules can be under source control
- can turn off a single systemd service instead of multiple cron jobs

**Comment by malakai97** [comment]
Assigning myself because I think I'm the only one who has used it.  Should be less cumbersome outside of rails.

**Comment by aelkiss** [comment]
Let's do this after we have the integration tests and something that works from the command line to start a dataset build.

**Comment by aelkiss** [comment]
Related to #53

**Comment by aelkiss** [comment]
Migrated to HTREPO-111
